name: Build Python Application

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install auto-py-to-exe

      - name: Create build windows
        if: startsWith(matrix.os, 'windows-')
        run: pyinstaller --noconfirm --onefile --add-data "template;template/" --add-data "fake;fake/" --add-data "parsers.py;." --add-data "utils.py;." --name "TABLEcreator[Windows].exe" "TABLEcreator.py"

      - name: Create build linux
        if: startsWith(matrix.os, 'ubuntu-')
        run: pyinstaller --noconfirm --onefile --add-data "template:template/" --add-data "fake:fake/" --add-data "parsers.py:." --add-data "utils.py:." --name "TABLEcreator[Linux].bin" "TABLEcreator.py"

      - name: Upload build windows
        uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows-')
        with:
          name: TABLEcreator[Windows].exe
          path: ./dist/TABLEcreator[Windows].exe

      - name: Upload build linux
        uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu-')
        with:
          name: TABLEcreator[Linux].bin
          path: ./dist/TABLEcreator[Linux].bin

  publish:
    needs: build
    
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact from windows-latest
        uses: actions/download-artifact@v4
        with:
          name: TABLEcreator[Windows].exe
          path: out

      - name: Download artifact from ubuntu-latest
        uses: actions/download-artifact@v4
        with:
          name: TABLEcreator[Linux].bin
          path: out

      - name: Create version
        id: create_version
        shell: python
        run: |
          from datetime import datetime
          from os import getenv
          
          DATE_Y = int(datetime.now().strftime("%y"))
          DATE_M = int(datetime.now().strftime("%m"))
          DATE_D = int(datetime.now().strftime("%d"))
          TIME = str(int(datetime.now().strftime("%H%M%S"))).rjust(6, "0")
          
          VERSION = f"v{DATE_Y}.{DATE_M}.{DATE_D}.{TIME}"
          
          print(VERSION)

          with open(file=getenv("GITHUB_OUTPUT"), mode="a") as github_output_file:
              github_output_file.write(f"version={VERSION}")
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "TABLE Creator"
          tag_name: ${{ steps.create_version.outputs.version }}
          body: ${{ steps.create_version.outputs.version }}
          files: |
            ./out/TABLEcreator[Windows].exe
            ./out/TABLEcreator[Linux].bin
